# Generated by Django 5.1.15 on 2026-07-23 06:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.CharField(help_text='Unique plot reference.', max_length=40, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('boundary', models.JSONField(blank=True, help_text="GeoJSON Polygon drawn on the map. Stored as {'type': 'Polygon', ...}.", null=True)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Area (acres)')),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('loam', 'Loam'), ('sandy_loam', 'Sandy loam'), ('clay_loam', 'Clay loam'), ('clay', 'Clay'), ('silt', 'Silt'), ('saline', 'Saline / sodic')], default='loam', max_length=20)),
                ('irrigation_type', models.CharField(choices=[('canal', 'Canal'), ('tubewell', 'Tubewell'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('rainfed', 'Rainfed'), ('mixed', 'Canal + tubewell')], default='canal', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fallow', 'Fallow'), ('harvested', 'Harvested'), ('retired', 'Retired')], db_index=True, default='active', max_length=12)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('critical', 'Critical'), ('unknown', 'Not assessed')], db_index=True, default='unknown', max_length=12)),
                ('latest_ndvi', models.FloatField(blank=True, null=True)),
                ('ndvi_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farmers.farmer')),
                ('officer', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('land_prep', 'Land preparation'), ('sowing', 'Sowing'), ('irrigation', 'Irrigation'), ('fertiliser', 'Fertiliser'), ('pesticide', 'Crop protection'), ('scouting', 'Scouting'), ('harvest', 'Harvest'), ('other', 'Other')], default='other', max_length=20)),
                ('performed_on', models.DateField(db_index=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crops.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fields.field')),
            ],
            options={
                'verbose_name_plural': 'farm activities',
                'ordering': ('-performed_on',),
            },
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['farmer', 'status'], name='fields_fiel_farmer__a41727_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['health'], name='fields_fiel_health_06bab3_idx'),
        ),
    ]
