# Generated by Django 5.1.15 on 2026-07-23 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_on', models.DateField(db_index=True)),
                ('source', models.CharField(default='Sentinel-2', help_text='Satellite or drone the imagery came from.', max_length=60)),
                ('red_band', models.ImageField(blank=True, help_text='Red band raster. Leave empty when uploading a single RGB image.', null=True, upload_to='ndvi/red/')),
                ('nir_band', models.ImageField(blank=True, help_text='Near-infrared band raster.', null=True, upload_to='ndvi/nir/')),
                ('rgb_image', models.ImageField(blank=True, help_text='Single RGB image. Processed with a visible-band index (VARI).', null=True, upload_to='ndvi/rgb/')),
                ('overlay', models.ImageField(blank=True, null=True, upload_to='ndvi/overlay/')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('processing', 'Processing'), ('done', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('index_used', models.CharField(blank=True, default='NDVI', max_length=10)),
                ('mean_index', models.FloatField(blank=True, null=True)),
                ('min_index', models.FloatField(blank=True, null=True)),
                ('max_index', models.FloatField(blank=True, null=True)),
                ('healthy_pct', models.FloatField(default=0)),
                ('moderate_pct', models.FloatField(default=0)),
                ('poor_pct', models.FloatField(default=0)),
                ('critical_pct', models.FloatField(default=0)),
                ('health_score', models.FloatField(default=0, help_text='0-100 score derived from the class distribution.')),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_records', to='fields.field')),
            ],
            options={
                'verbose_name': 'NDVI record',
                'verbose_name_plural': 'NDVI records',
                'ordering': ('-captured_on', '-created_at'),
                'indexes': [models.Index(fields=['field', '-captured_on'], name='ndvi_ndvire_field_i_fdbe65_idx')],
            },
        ),
    ]
