# Generated by Django 5.1.15 on 2026-07-23 06:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('cnic', models.CharField(help_text='Format: 00000-0000000-0', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter the CNIC as 13 digits in the format 00000-0000000-0.', regex='^\\d{5}-\\d{7}-\\d$')], verbose_name='CNIC')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('village', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, max_length=120)),
                ('province', models.CharField(blank=True, default='Punjab', max_length=120)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='farmers/')),
                ('total_land_acres', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total land (acres)')),
                ('registration_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending verification')], db_index=True, default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('portal_user', models.OneToOneField(blank=True, help_text='Optional login so the farmer can see their own fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['status', 'city'], name='farmers_far_status_a0d459_idx'), models.Index(fields=['registration_date'], name='farmers_far_registr_694913_idx')],
            },
        ),
    ]
