# Generated by Django 5.1.15 on 2026-07-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('feels_like_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('rain_probability_pct', models.FloatField(blank=True, null=True)),
                ('precipitation_mm', models.FloatField(blank=True, null=True)),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True)),
                ('wind_direction_deg', models.FloatField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('condition_code', models.IntegerField(blank=True, null=True)),
                ('condition_text', models.CharField(blank=True, max_length=80)),
                ('forecast', models.JSONField(blank=True, default=list, help_text='List of daily forecast dictionaries.')),
                ('source', models.CharField(default='open-meteo', max_length=40)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='fields.field')),
            ],
            options={
                'verbose_name': 'weather record',
                'verbose_name_plural': 'weather records',
                'ordering': ('-fetched_at',),
                'indexes': [models.Index(fields=['field', '-fetched_at'], name='weather_wea_field_i_a4e603_idx')],
            },
        ),
    ]
