# Generated by Django 5.1.15 on 2026-07-23 06:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('cereal', 'Cereal'), ('fibre', 'Fibre'), ('oilseed', 'Oilseed'), ('pulse', 'Pulse'), ('fodder', 'Fodder'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('sugar', 'Sugar')], db_index=True, default='cereal', max_length=20)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid'), ('perennial', 'Perennial')], db_index=True, default='kharif', max_length=12)),
                ('planting_date', models.DateField(db_index=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Area sown (acres)')),
                ('production_tonnes', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production (tonnes)')),
                ('price_per_tonne', models.DecimalField(decimal_places=2, default=0, help_text='Farm-gate price used for the revenue figures.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], db_index=True, default='planned', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-planting_date',),
            },
        ),
    ]
