# Generated by Django 5.1.15 on 2026-07-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='fields.field'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['status', 'season'], name='crops_crop_status_eb869e_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['name'], name='crops_crop_name_a88701_idx'),
        ),
    ]
